# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cd /kaggle/input/universal-bank

/kaggle/input/universal-bank


In [3]:
df=pd.read_csv("UnivBank.csv",na_values=['.',':','?','!','@','#','$','%','^','&','*',','])

In [4]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0          0.0              0                 1.0         0.0       0   
1          0.0              0                 1.0         0.0       0   
2          0.0              0                 0.0         0.0       0   
3          0.0              0                 0.0         NaN       0   
4          0.0              0                 0.0         0.0       0   
...        ...            ...                 ...         ...     ...   
4995       0.0              0                 0.0         0.0       1   
4996      85.0              0                 0.0         0.0       1   
4997       0.0              0                 0.0         0.0       0   
4998       0.0              0                 0.0         0.0       1   
4999       0.0              0                 0.0         0.0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [5]:
df.describe()

ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000   
mean   2500.500000    45.338400    20.104600    73.774200  93152.503000   
std    1443.520003    11.463166    11.467954    46.033729   2121.852197   
min       1.000000    23.000000    -3.000000     8.000000   9307.000000   
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000   
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000   
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000   
max    5000.000000    67.000000    43.000000   224.000000  96651.000000   

            Family        CCAvg    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000  4998.000000    5000.000000   
mean      2.396400     1.937938     1.881000    56.521409       0.096000   
std       1.147663     1.747659     0.839869   101.727873       0.294621   
min       1.000000     0.000000     1.000000     0.000000       0.000000   
25%       1.000000     0.700000     1.000000     0.000000       0.000000   
50%       2.000000     1.500000     2.000000     0.000000       0.000000   
75%       3.000000     2.500000     3.000000   101.000000       0.000000   
max       4.000000    10.000000     3.000000   635.000000       1.000000   

       Securities Account   CD Account       Online   CreditCard  
count         4998.000000  4999.000000  5000.000000  5000.000000  
mean             0.104442     0.060412     0.596800     0.294000  
std              0.305863     0.238273     0.490589     0.455637  
min              0.000000     0.000000     0.000000     0.000000  
25%              0.000000     0.000000     0.000000     0.000000  
50%              0.000000     0.000000     1.000000     0.000000  
75%              0.000000     0.000000     1.000000     1.000000  
max              1.000000     1.000000     1.000000     1.000000

In [6]:
df.dtypes

ID                      int64
Age                     int64
Experience              int64
Income                  int64
ZIP Code                int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage              float64
Personal Loan           int64
Securities Account    float64
CD Account            float64
Online                  int64
CreditCard              int64
dtype: object

In [7]:
df.nunique()

ID                    5000
Age                     45
Experience              47
Income                 162
ZIP Code               467
Family                   4
CCAvg                  108
Education                3
Mortgage               347
Personal Loan            2
Securities Account       2
CD Account               2
Online                   2
CreditCard               2
dtype: int64

In [8]:
df = df.drop(["ZIP Code","ID"], axis=1)

In [9]:
df.isnull().sum()

Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              2
Personal Loan         0
Securities Account    2
CD Account            1
Online                0
CreditCard            0
dtype: int64

In [10]:
df

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0      25           1      49       4    1.6          1       0.0   
1      45          19      34       3    1.5          1       0.0   
2      39          15      11       1    1.0          1       0.0   
3      35           9     100       1    2.7          2       0.0   
4      35           8      45       4    1.0          2       0.0   
...   ...         ...     ...     ...    ...        ...       ...   
4995   29           3      40       1    1.9          3       0.0   
4996   30           4      15       4    0.4          1      85.0   
4997   63          39      24       2    0.3          3       0.0   
4998   65          40      49       3    0.5          2       0.0   
4999   28           4      83       3    0.8          1       0.0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
0                 0                 1.0         0.0       0           0  
1                 0                 1.0         0.0       0           0  
2                 0                 0.0         0.0       0           0  
3                 0                 0.0         NaN       0           0  
4                 0                 0.0         0.0       0           1  
...             ...                 ...         ...     ...         ...  
4995              0                 0.0         0.0       1           0  
4996              0                 0.0         0.0       1           0  
4997              0                 0.0         0.0       0           0  
4998              0                 0.0         0.0       1           0  
4999              0                 0.0         0.0       1           1  

[5000 rows x 12 columns]

In [11]:
df.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

In [12]:
for col in ['Education','Securities Account','CD Account','Online','CreditCard','Family']:
    df[col] = df[col].astype('category')

In [13]:
cat_cols=['Education','Securities Account','CD Account','Online','CreditCard']

In [14]:
cat_cols

['Education', 'Securities Account', 'CD Account', 'Online', 'CreditCard']

In [15]:
num_cols=['Age', 'CCAvg', 'Experience', 'Income', 'Mortgage']

In [16]:
cat_cols

['Education', 'Securities Account', 'CD Account', 'Online', 'CreditCard']

## Splitting

In [17]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [18]:
X = df.drop('Personal Loan',axis=1)
y= df['Personal Loan']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=255, stratify=y)

In [20]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3500, 11)
(1500, 11)
(3500,)
(1500,)


In [21]:
df["Personal Loan"].value_counts(normalize=True)

0    0.904
1    0.096
Name: Personal Loan, dtype: float64

In [22]:
y_train.value_counts(normalize=True)

0    0.904
1    0.096
Name: Personal Loan, dtype: float64

In [23]:
y_test.value_counts(normalize=True)

0    0.904
1    0.096
Name: Personal Loan, dtype: float64

## Imputation

In [24]:
from sklearn.impute import SimpleImputer
imputer_num = SimpleImputer(strategy='median')
imputer_num = imputer_num.fit(X_train[num_cols])
X_train_num_imp = pd.DataFrame(imputer_num.transform(X_train[num_cols]), columns=(X_train[num_cols]).columns)
X_test_num_imp = pd.DataFrame(imputer_num.transform(X_test[num_cols]), columns=(X_test[num_cols]).columns)

In [25]:
X_train_num_imp.isnull().sum()

Age           0
CCAvg         0
Experience    0
Income        0
Mortgage      0
dtype: int64

In [26]:
X_test_num_imp.isnull().sum()

Age           0
CCAvg         0
Experience    0
Income        0
Mortgage      0
dtype: int64

In [27]:
imputer_cat = SimpleImputer(strategy='most_frequent')
imputer_cat = imputer_cat.fit(X_train[cat_cols])
X_train_cat_imp = pd.DataFrame(imputer_cat.transform(X_train[cat_cols]), columns=(X_train[cat_cols]).columns)
X_test_cat_imp = pd.DataFrame(imputer_cat.transform(X_test[cat_cols]), columns=(X_test[cat_cols]).columns)

In [28]:
X_train_cat_imp.isnull().sum()

Education             0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [29]:
X_test_cat_imp.isnull().sum()

Education             0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

## Standardisation

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler = scaler.fit(X_train[num_cols])
X_train_num_std = pd.DataFrame(scaler.transform(X_train_num_imp), columns=X_train_num_imp.columns)
X_test_num_std = pd.DataFrame(scaler.transform(X_test_num_imp), columns=X_test_num_imp.columns)

In [31]:
X_train_num_std.isnull().sum()

Age           0
CCAvg         0
Experience    0
Income        0
Mortgage      0
dtype: int64

In [32]:
X_test_num_std.isnull().sum()

Age           0
CCAvg         0
Experience    0
Income        0
Mortgage      0
dtype: int64

## Dummification

In [33]:
X_train_cat_dum = pd.get_dummies((X_train_cat_imp),drop_first=True)
X_test_cat_dum = pd.get_dummies((X_test_cat_imp),drop_first=True)

In [34]:
X_train_cat_dum

Education  Securities Account  CD Account  Online  CreditCard
0           3.0                 0.0         0.0     0.0         0.0
1           1.0                 0.0         0.0     1.0         1.0
2           2.0                 0.0         0.0     0.0         0.0
3           3.0                 1.0         0.0     0.0         0.0
4           2.0                 0.0         1.0     1.0         1.0
...         ...                 ...         ...     ...         ...
3495        1.0                 0.0         0.0     1.0         0.0
3496        2.0                 0.0         0.0     0.0         0.0
3497        2.0                 0.0         1.0     1.0         0.0
3498        2.0                 0.0         0.0     0.0         0.0
3499        2.0                 0.0         0.0     0.0         0.0

[3500 rows x 5 columns]

In [35]:
X_test_cat_dum

Education  Securities Account  CD Account  Online  CreditCard
0           3.0                 0.0         0.0     0.0         0.0
1           2.0                 0.0         0.0     0.0         1.0
2           3.0                 0.0         0.0     0.0         0.0
3           1.0                 0.0         0.0     0.0         0.0
4           1.0                 1.0         0.0     0.0         0.0
...         ...                 ...         ...     ...         ...
1495        2.0                 0.0         0.0     0.0         0.0
1496        3.0                 0.0         0.0     1.0         0.0
1497        2.0                 1.0         1.0     1.0         1.0
1498        1.0                 0.0         0.0     1.0         0.0
1499        1.0                 0.0         0.0     1.0         0.0

[1500 rows x 5 columns]

In [36]:
X_train_num_std = X_train_num_std.reset_index()
X_train_num_std

index       Age     CCAvg  Experience    Income  Mortgage
0         0 -0.365348 -0.823094   -0.433181 -0.184525 -0.547282
1         1  0.949574 -0.936589    1.057179  0.356759 -0.547282
2         2 -0.190025  0.879329   -0.257845  1.114557 -0.547282
3         3  1.212558  0.198360    1.320184  0.031988 -0.547282
4         4 -1.592608 -0.085377   -1.660537 -0.336085  0.958665
...     ...       ...       ...         ...       ...       ...
3495   3495 -0.978978  0.595592   -0.959191  2.695106  3.579405
3496   3496  0.774251 -0.085377    0.881842  0.096942 -0.547282
3497   3497  0.248282  0.765834    0.355833  1.915657  3.814098
3498   3498  0.248282  0.482097    0.268165 -0.076268 -0.547282
3499   3499 -1.066639  0.141612   -1.134527 -0.552599  1.476946

[3500 rows x 6 columns]

In [37]:
X_train_num_std = X_train_num_std.drop(["index"], axis=1)

In [38]:
X_train_num_std

Age     CCAvg  Experience    Income  Mortgage
0    -0.365348 -0.823094   -0.433181 -0.184525 -0.547282
1     0.949574 -0.936589    1.057179  0.356759 -0.547282
2    -0.190025  0.879329   -0.257845  1.114557 -0.547282
3     1.212558  0.198360    1.320184  0.031988 -0.547282
4    -1.592608 -0.085377   -1.660537 -0.336085  0.958665
...        ...       ...         ...       ...       ...
3495 -0.978978  0.595592   -0.959191  2.695106  3.579405
3496  0.774251 -0.085377    0.881842  0.096942 -0.547282
3497  0.248282  0.765834    0.355833  1.915657  3.814098
3498  0.248282  0.482097    0.268165 -0.076268 -0.547282
3499 -1.066639  0.141612   -1.134527 -0.552599  1.476946

[3500 rows x 5 columns]

In [39]:
X_train_cat_dum = X_train_cat_dum.reset_index()
X_train_cat_dum

index  Education  Securities Account  CD Account  Online  CreditCard
0         0        3.0                 0.0         0.0     0.0         0.0
1         1        1.0                 0.0         0.0     1.0         1.0
2         2        2.0                 0.0         0.0     0.0         0.0
3         3        3.0                 1.0         0.0     0.0         0.0
4         4        2.0                 0.0         1.0     1.0         1.0
...     ...        ...                 ...         ...     ...         ...
3495   3495        1.0                 0.0         0.0     1.0         0.0
3496   3496        2.0                 0.0         0.0     0.0         0.0
3497   3497        2.0                 0.0         1.0     1.0         0.0
3498   3498        2.0                 0.0         0.0     0.0         0.0
3499   3499        2.0                 0.0         0.0     0.0         0.0

[3500 rows x 6 columns]

In [40]:
X_train_cat_dum = X_train_cat_dum.drop(["index"], axis=1)

In [41]:
X_train_cat_dum

Education  Securities Account  CD Account  Online  CreditCard
0           3.0                 0.0         0.0     0.0         0.0
1           1.0                 0.0         0.0     1.0         1.0
2           2.0                 0.0         0.0     0.0         0.0
3           3.0                 1.0         0.0     0.0         0.0
4           2.0                 0.0         1.0     1.0         1.0
...         ...                 ...         ...     ...         ...
3495        1.0                 0.0         0.0     1.0         0.0
3496        2.0                 0.0         0.0     0.0         0.0
3497        2.0                 0.0         1.0     1.0         0.0
3498        2.0                 0.0         0.0     0.0         0.0
3499        2.0                 0.0         0.0     0.0         0.0

[3500 rows x 5 columns]

In [42]:
X_test_num_std = X_test_num_std.reset_index()
X_test_num_std

index       Age     CCAvg  Experience    Income  Mortgage
0         0 -1.417285  0.311855   -1.397532  0.789786 -0.547282
1         1  0.861912 -0.255620    0.881842 -1.115534  0.342596
2         2 -0.014702  4.567914   -0.433181  2.781712 -0.547282
3         3 -1.680270  0.311855   -1.572869  0.183548  1.398715
4         4 -0.102364  0.538845   -0.170177 -0.119571 -0.547282
...     ...       ...       ...         ...       ...       ...
1495   1495  1.124897 -0.596104    1.144847 -1.267094 -0.547282
1496   1496 -0.891317  1.163067   -1.309864  0.248502 -0.547282
1497   1497  1.212558  2.581753    1.320184  2.305382 -0.547282
1498   1498 -1.066639 -0.369115   -1.046859 -0.119571 -0.547282
1499   1499  0.248282 -1.106831    0.180496  1.006300 -0.547282

[1500 rows x 6 columns]

In [43]:
X_test_num_std = X_test_num_std.drop(["index"], axis=1)

In [44]:
X_test_num_std

Age     CCAvg  Experience    Income  Mortgage
0    -1.417285  0.311855   -1.397532  0.789786 -0.547282
1     0.861912 -0.255620    0.881842 -1.115534  0.342596
2    -0.014702  4.567914   -0.433181  2.781712 -0.547282
3    -1.680270  0.311855   -1.572869  0.183548  1.398715
4    -0.102364  0.538845   -0.170177 -0.119571 -0.547282
...        ...       ...         ...       ...       ...
1495  1.124897 -0.596104    1.144847 -1.267094 -0.547282
1496 -0.891317  1.163067   -1.309864  0.248502 -0.547282
1497  1.212558  2.581753    1.320184  2.305382 -0.547282
1498 -1.066639 -0.369115   -1.046859 -0.119571 -0.547282
1499  0.248282 -1.106831    0.180496  1.006300 -0.547282

[1500 rows x 5 columns]

In [45]:
X_test_cat_dum = X_test_cat_dum.reset_index()
X_test_cat_dum

index  Education  Securities Account  CD Account  Online  CreditCard
0         0        3.0                 0.0         0.0     0.0         0.0
1         1        2.0                 0.0         0.0     0.0         1.0
2         2        3.0                 0.0         0.0     0.0         0.0
3         3        1.0                 0.0         0.0     0.0         0.0
4         4        1.0                 1.0         0.0     0.0         0.0
...     ...        ...                 ...         ...     ...         ...
1495   1495        2.0                 0.0         0.0     0.0         0.0
1496   1496        3.0                 0.0         0.0     1.0         0.0
1497   1497        2.0                 1.0         1.0     1.0         1.0
1498   1498        1.0                 0.0         0.0     1.0         0.0
1499   1499        1.0                 0.0         0.0     1.0         0.0

[1500 rows x 6 columns]

In [46]:
X_test_cat_dum = X_test_cat_dum.drop(["index"], axis=1)

In [47]:
X_test_cat_dum

Education  Securities Account  CD Account  Online  CreditCard
0           3.0                 0.0         0.0     0.0         0.0
1           2.0                 0.0         0.0     0.0         1.0
2           3.0                 0.0         0.0     0.0         0.0
3           1.0                 0.0         0.0     0.0         0.0
4           1.0                 1.0         0.0     0.0         0.0
...         ...                 ...         ...     ...         ...
1495        2.0                 0.0         0.0     0.0         0.0
1496        3.0                 0.0         0.0     1.0         0.0
1497        2.0                 1.0         1.0     1.0         1.0
1498        1.0                 0.0         0.0     1.0         0.0
1499        1.0                 0.0         0.0     1.0         0.0

[1500 rows x 5 columns]

In [48]:
final_X_train = pd.concat([X_train_num_std, X_train_cat_dum], axis=1)

In [49]:
final_X_test = pd.concat([X_test_num_std, X_test_cat_dum], axis=1)

In [50]:
final_X_train.isnull().sum()

Age                   0
CCAvg                 0
Experience            0
Income                0
Mortgage              0
Education             0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [51]:
final_X_test.isnull().sum()

Age                   0
CCAvg                 0
Experience            0
Income                0
Mortgage              0
Education             0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [52]:
final_X_train

Age     CCAvg  Experience    Income  Mortgage  Education  \
0    -0.365348 -0.823094   -0.433181 -0.184525 -0.547282        3.0   
1     0.949574 -0.936589    1.057179  0.356759 -0.547282        1.0   
2    -0.190025  0.879329   -0.257845  1.114557 -0.547282        2.0   
3     1.212558  0.198360    1.320184  0.031988 -0.547282        3.0   
4    -1.592608 -0.085377   -1.660537 -0.336085  0.958665        2.0   
...        ...       ...         ...       ...       ...        ...   
3495 -0.978978  0.595592   -0.959191  2.695106  3.579405        1.0   
3496  0.774251 -0.085377    0.881842  0.096942 -0.547282        2.0   
3497  0.248282  0.765834    0.355833  1.915657  3.814098        2.0   
3498  0.248282  0.482097    0.268165 -0.076268 -0.547282        2.0   
3499 -1.066639  0.141612   -1.134527 -0.552599  1.476946        2.0   

      Securities Account  CD Account  Online  CreditCard  
0                    0.0         0.0     0.0         0.0  
1                    0.0         0.0     1.0         1.0  
2                    0.0         0.0     0.0         0.0  
3                    1.0         0.0     0.0         0.0  
4                    0.0         1.0     1.0         1.0  
...                  ...         ...     ...         ...  
3495                 0.0         0.0     1.0         0.0  
3496                 0.0         0.0     0.0         0.0  
3497                 0.0         1.0     1.0         0.0  
3498                 0.0         0.0     0.0         0.0  
3499                 0.0         0.0     0.0         0.0  

[3500 rows x 10 columns]

In [53]:
final_X_test

Age     CCAvg  Experience    Income  Mortgage  Education  \
0    -1.417285  0.311855   -1.397532  0.789786 -0.547282        3.0   
1     0.861912 -0.255620    0.881842 -1.115534  0.342596        2.0   
2    -0.014702  4.567914   -0.433181  2.781712 -0.547282        3.0   
3    -1.680270  0.311855   -1.572869  0.183548  1.398715        1.0   
4    -0.102364  0.538845   -0.170177 -0.119571 -0.547282        1.0   
...        ...       ...         ...       ...       ...        ...   
1495  1.124897 -0.596104    1.144847 -1.267094 -0.547282        2.0   
1496 -0.891317  1.163067   -1.309864  0.248502 -0.547282        3.0   
1497  1.212558  2.581753    1.320184  2.305382 -0.547282        2.0   
1498 -1.066639 -0.369115   -1.046859 -0.119571 -0.547282        1.0   
1499  0.248282 -1.106831    0.180496  1.006300 -0.547282        1.0   

      Securities Account  CD Account  Online  CreditCard  
0                    0.0         0.0     0.0         0.0  
1                    0.0         0.0     0.0         1.0  
2                    0.0         0.0     0.0         0.0  
3                    0.0         0.0     0.0         0.0  
4                    1.0         0.0     0.0         0.0  
...                  ...         ...     ...         ...  
1495                 0.0         0.0     0.0         0.0  
1496                 0.0         0.0     1.0         0.0  
1497                 1.0         1.0     1.0         1.0  
1498                 0.0         0.0     1.0         0.0  
1499                 0.0         0.0     1.0         0.0  

[1500 rows x 10 columns]

# Model building

## Logistic Regression

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
lr = LogisticRegression()
lr = lr.fit(final_X_train,y_train)

In [56]:
y_train_preds = lr.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
y_test_preds = lr.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [58]:
from sklearn.metrics import confusion_matrix
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[3124,   40],
       [ 134,  202]])

In [59]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[1342,   14],
       [  59,   85]])

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

0.9502857142857143

In [61]:
accuracy_score(y_test,y_test_preds)

0.9513333333333334

## Decision Trees

In [62]:
from sklearn import tree

In [63]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(final_X_train, y_train)

In [64]:
y_train_preds = dt.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [65]:
y_test_preds = dt.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [66]:
from sklearn.metrics import confusion_matrix
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[3164,    0],
       [   0,  336]])

In [67]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[1322,   34],
       [  29,  115]])

In [68]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

1.0

In [69]:
accuracy_score(y_test,y_test_preds)

0.958

## Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
rfc = RandomForestClassifier(n_estimators = 50, max_depth = 10, criterion="entropy")
rfc = rfc.fit(final_X_train, y_train)

In [72]:
y_train_preds = rfc.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [73]:
y_test_preds = rfc.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [74]:
from sklearn.metrics import confusion_matrix
confusionma2trix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[1322,   34],
       [  29,  115]])

In [75]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[1344,   12],
       [  37,  107]])

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

0.9894285714285714

In [77]:
accuracy_score(y_test,y_test_preds)

0.9673333333333334

## XG Boost

In [78]:
!pip3 install xgboost

In [79]:
from xgboost import XGBClassifier

In [80]:
xgb = XGBClassifier()
xgb = xgb.fit(final_X_train, y_train)

In [81]:
y_train_preds = xgb.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [82]:
y_test_preds = xgb.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [83]:
from sklearn.metrics import confusion_matrix
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[3164,    0],
       [   0,  336]])

In [84]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[1346,   10],
       [  30,  114]])

In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

1.0

In [86]:
accuracy_score(y_test,y_test_preds)

0.9733333333333334

# KNN

In [87]:
from sklearn.neighbors import KNeighborsClassifier

In [88]:
knn = KNeighborsClassifier()
knn = knn.fit(final_X_train, y_train)

In [89]:
y_train_preds = knn.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [90]:
y_test_preds = knn.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [91]:
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[3154,   10],
       [ 114,  222]])

In [92]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[1351,    5],
       [  59,   85]])

In [93]:
accuracy_score(y_train,y_train_preds)

0.9645714285714285

In [94]:
accuracy_score(y_test,y_test_preds)

0.9573333333333334

In [95]:
#KNN